[package]
name = "cdumay_rest_client"
version = "0.3.0"

authors = ["Cédric Dumay <cedric.dumay@gmail.com>"]
categories = ["authentication",  "data-structures", "encoding", "parsing", "web-programming::http-client"]
description = """A library to call remote REST API application"""
documentation = "https://docs.rs/cdumay_rest_client"
edition = "2021"
homepage =  "https://github.com/cdumay/rust-cdumay_rest_client"
keywords = ["http", "serde", "REST"]
license = "BSD-3-Clause"
readme = "README.md"
repository = "https://github.com/cdumay/rust-cdumay_rest_client"

[badges]
gitlab = { repository = "cdumay/rust-cdumay_http_client" }
travis-ci = { repository = "cdumay/rust-cdumay_http_client" }
maintenance = { status = "as-is" }

[dependencies]
cdumay_error = "0.3.0"
cdumay_http_client = "0.3.2"
reqwest = { version = "0.12.5", features = ["json", "blocking"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
log = "0.4.22"

[dev-dependencies]
simple_logger = "5.0.0"